### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by TheHeadlessSourceMan** [nyxiereal/XToolbox#38]
It would be nice to be able to quickly install this collection of tools using the chocolatey package manager.

**Comment by sudosign** [comment]
https://github.com/xemulat/XToolbox/issues/36#issuecomment-1986885962 they were thinking about using winget but chocolatey or scoop would likely work aswell though not prebuilt

**Comment by xemulat** [comment]
Well, I think I'll reimplement the winget check and installer from CTT.

**Comment by xemulat** [comment]
I just realized you were thinking about deploying it as a choco package. I'll do that if I don't forget about it.

**Comment by nyxiereal** [comment]
I think that XTB should be as portable as possible, and that releasing a choco package will only complicate things. And to be honest, I have no clue how to deploy choco packages. I'll *maybe* reconsider in the future, but not for now.
